version: '3'
services:
  api:
    build: ./api
    ports:
      - "8080:5000"
    depends_on:
      - rabbitmq

    networks:
      - my_network
    command: sh -c "sleep 10 && python routes.py"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

  movie_maker:
    build: ./movie_maker
    depends_on:
      - rabbitmq
      - api
    networks:
      - my_network
    command: sh -c "sleep 10 && python messaging_system/video_queue.py"

networks:
    my_network:
      driver: bridge


